#server.error.include-message=ALWAYS
#spring.datasource.url=jdbc:postgresql://localhost:5432/Customer
#spring.datasource.username=lirus
#spring.datasource.password=lirus
#spring.jpa.database=POSTGRESQL
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update

server:
  port: 8082
  error:
    include-message: ALWAYS

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Customer
    username: lirus
    password: lirus
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


